name: "run tests"
description: "set up and run the full environment unit test suite"
inputs:
  use-tag:
    description: "Whether or not to test against the tag"
    required: true
    default: false
  CHECKOUT_TOKEN:
    description: "checkout token for internal repositories"
    required: false
    default: ""
runs:
  using: "composite"
  # Maybe someday default shell will be supported for actions, not just workflows
  # defaults:
  #   run:
  #     shell: bash --login -eo pipefail {0}
  steps:
    - run: |
        echo $TOKEN
        echo $${{ inputs.CHECKOUT_TOKEN }}
        git clone "https://username:${TOKEN}@github.com/pcdshub/pytmc" --depth 1
        cd pytmc
        pwd
        git submodule update --init --recursive
      env:
        TOKEN: ${{ inputs.CHECKOUT_TOKEN }}
      shell: bash --login -eo pipefail {0}