name: Sample composite workflow

on:
  pull_request:
  release:
    types:
      - published

env:
  MPLBACKEND: "agg"
  QT_QPA_PLATFORM: "offscreen"

jobs:
  # The latest deployed env OR the proposed env in a PR
  current-tests:
    defaults:
      run:
        shell: bash --login -eo pipefail {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/run_tests
      with:
        use-tag: true
        CHECKOUT_TOKEN: ${{ secrets.TOKEN || github.token }}